### ISSUE TITLE
The section "Making the Session Manager the Default One" can be removed

### ISSUE THREAD

**Issue by froschdesign** [modir/laminas-book#5]
The following section can be removed because the session manager is already the default one:

> Making the Session Manager the Default One
> In Laminas, many components use the session manager implicitly (for example, @FlashMessenger[Laminas\Mvc\Plugin\FlashMessenger] controller plugin and view helper uses session to save messages between HTTP requests). To let such components use the session manager you just configured, you'll have to make it "the default one" by instantiating it as early as possible. For example, you can instantiate the session manager in your module's onBootstrap() method, as follows:
> 

https://modir.github.io/laminas-book/session/#making-the-session-manager-the-default-one

See:

> enable_default_container_manager: whether to inject the created instance
> as the default manager for Container instances. The default value for
> this is true; set it to false to disable.

https://github.com/laminas/laminas-session/blob/e733d986b30704831c6ec530d06688faf6f0856a/src/Service/SessionManagerFactory.php#L57-L59

https://github.com/laminas/laminas-session/blob/e733d986b30704831c6ec530d06688faf6f0856a/src/Service/SessionManagerFactory.php#L141-L148

**Comment by modir** [comment]
Thanks. I just removed it now.
